### ISSUE TITLE
Citizens Reload Command partially breaks Save Command

### ISSUE THREAD

**Issue by Ditronian** [CitizensDev/Citizens2#1211]
It seems that after performing a '/citizens reload' command, Citizens will no longer save the removal of any npcs when you do /citizens save.  Other commands such as '/npc rename' appear unaffected and save normally.

I have simplified the steps to replicate the problem to the following:

1. Create a NPC.
2. Execute /citizens save (NPC is saved in saves.yml)
3. Execute /citizens reload
4. Execute /npc remove (NPC is removed in game)
5. Execute /citizens save (NPC is **not** removed from the saves.yml file)
6. Execute /citizens reload (Removed NPC reappears due to removal not being saved.)

At this point the removal of **any** NPCs is impossible to save until a Server Restart is performed.  At no point during the troubleshooting was there any console errors.

This problem has plagued my servers since I started using Citizens back in Minecraft 1.11, but until now I haven't been able to narrow down the problem to a specific cause in an isolated environment.  For this troubleshooting, I was using the Spigot 1.12 and Citizens 2.0.2, with no other plugins installed.

**Comment by Ditronian** [comment]
Addition: The /npc skin [YourUserName] command also peculiarly stops working after /citizens reload.  You may still set skins with other players' usernames, but using your own will result in a Steve skin that sticks after server restarts.

**Comment by RokkoEffe** [comment]
This problem, maybe, is connected with my similar issue https://github.com/CitizensDev/Citizens2/issues/1188
Have you tried last #1484 snapshot? My problem was fixed after I installed this version.

**Comment by Ditronian** [comment]
Yes I was running #1484 when I did the testing, I just tried it again on a fresh install of #1485 (with it being the only plugin) and the issue remains.

This is a very old problem of mine, and should only take you a minute or so to replicate.

**Comment by Kequo** [comment]
This is an issue I am experiencing myself, and I would also like a solution.

**Comment by mcmonkey4eva** [comment]
I believe this was fixed at some point.
If it's not, please open a new issue.
