### ISSUE TITLE
Traversing Nether Portals breaks Navigation

### ISSUE THREAD

**Issue by SnoFox** [CitizensDev/Citizens2#1568]
The output of command `/version` on my server is: **git-Spigot-6b015b4-94b8708 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)**
The output of command `/version citizens` on my server is: **2.0.24-SNAPSHOT (build 1570)**

When Citizens NPCs move into a Nether portal, Minecraft will teleport them. After teleport, Citizens is still protecting them, but NMS's AI takes over for movement. Doesn't affect Player NPCs; I've only tested with Ocelots so far.

Citizens configuration file is default; all I did was load the latest build.

Here's an example of my plugin pathing and forcing an NPC to stay in the same world, but fails pathing after going through the netherpotal: https://youtu.be/sXaGTIWXabg
Logs: https://gist.github.com/SnoFox/394657ea4f34d0b37e79f069faf9c294#file-2018-09-18-15-log

And another example, using just Citizens commands to create pathing and demonstration of NMS AI taking over: https://youtu.be/b1cLSsSV15c
Logs: https://gist.github.com/SnoFox/394657ea4f34d0b37e79f069faf9c294#file-2018-09-18-16-log

**Comment by SnoFox** [comment]
Workaround for those who don't want their NPCs to teleport: Cancel `EntityPortalEvent` if it's your entity

**Comment by fullwall** [comment]
Seems like a difficult problem with entities and changing worlds. I pushed a semi-fix for portals but may need more changes to deal with cross-world teleporting.

**Comment by mcmonkey4eva** [comment]
@SnoFox is there still trouble on the latest version?

**Comment by SnoFox** [comment]
Hey @mcmonkey4eva, apologies for never seeing this. It appears this is still an issue.

Here's the latest logs using **git-Spigot-573cdf2-dff66df (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)** and Citizens **2.0.24-SNAPSHOT (build 1604)**

All I can still gather is that it's triggering reliably after my turtle tries to navigate to a `Location` in deep water.

https://gist.github.com/SnoFox/bebdad48da5da0a70e2327dfdd4ca202

Perhaps other relevant information:
I have custom metadata on it to discover it as from my plugin, I've also turned off collision, turned on silence, and turned on swimming, using Citizens' `MetadataStore`

**Comment by SnoFox** [comment]
Hey @mcmonkey4eva, apologies again for not seeing this for so long. I think I've fixed my GitHub e-mails if you guys need any follow-up.

It appears to still be an issue on **git-Spigot-573cdf2-dff66df (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)** and **Citizens 2.0.24-SNAPSHOT (build 1604)**, though it seems like the changes in Spigot since I've last worked on this has caused my previous workaround to fail.

**Comment by mcmonkey4eva** [comment]
Possibly fixed in new builds (at https://ci.citizensnpcs.co/job/Citizens2/ ) by https://github.com/CitizensDev/Citizens2/commit/bbf3f281ebe9eaa0be76086ef566349f8246d57d

Please reply below if it isn't fixed yet.
