### ISSUE TITLE
Citizens NPC Player heads stuck facing upward after battling phantoms even after fixing pitch/yaw in saves

### ISSUE THREAD

**Issue by axemwa** [CitizensDev/Citizens2#1623]
Citizens NPC Player heads stuck facing upward after battling phantoms even after fixing pitch/yaw in saves.yml

- [Latest.log](https://pastebin.com/ksv7Ukzp)
- [Config.yml](https://pastebin.com/CtUmbWAY)
- [Saves.yml](https://pastebin.com/aH36W9bU)

The output of command `/version` on my server is: **(This server is running Paper version git-Paper-469 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT))**

The output of command `/version citizens` on my server is: **(Citizens version 2.0.24-SNAPSHOT (build 1592))**

**Comment by mcmonkey4eva** [comment]
Which NPC (id number) are you referring to? (There's a lot of them saved there)
Can you provide a screenshot of the how the NPC appears in game?

**Comment by axemwa** [comment]
The Guards with the 'joymo' skin NPC '72' and '157'

**Comment by axemwa** [comment]
![image](https://user-images.githubusercontent.com/37608633/49270423-47786600-f4b9-11e8-8a3c-278a21dcbb4d.png)

**Comment by axemwa** [comment]
ID is mentioned above

**Comment by mcmonkey4eva** [comment]
Can you try using `/npc lookclose` to make the NPC look at you? Does that fix their head direction?

**Comment by axemwa** [comment]
I did, but it only works if I turn path/waypoints off which stops them walking and when I walk away out of lookclose range and they fight the phantoms again their heads stuck looking up again

**Comment by mcmonkey4eva** [comment]
So:
To clarify my understanding: when they're walking around, the pitch (up/down angle) of their heads is stuck in place as whatever it was last forced into (in this case by fighting with something above them)?

**Comment by axemwa** [comment]
Yeah that's correct :)

**Comment by axemwa** [comment]
And if lookclose is on they do look at you but as soon as u leave, the npc head looks up again

**Comment by mcmonkey4eva** [comment]
This commit: https://github.com/CitizensDev/Citizens2/commit/9f9647a6152527dd8fecfb58c75d2de17ead9039 may be relevant here.

**Comment by axemwa** [comment]
Maybe, it does mention the pitch. I'm new to plugin development only made 1 so far so not too good at reading code yet lemme know if there anything else I can do to help

**Comment by mergu** [comment]
@Florenthz 
![image](https://user-images.githubusercontent.com/29823405/49349016-95869880-f676-11e8-8cef-78da577f4f71.png)

**Comment by Florenthz** [comment]
@mergu I found this friend:

03.12 18:46:09 [Server] INFO Florenthz issued server command: /citizens reload
03.12 18:46:09 [Server] WARN java.lang.IllegalArgumentException: unable to find valid entity superclass for class class net.citizensnpcs.nms.v1_13_R2.entity.WolfController$EntityWolfNPC
03.12 18:46:09 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.registerEntityClass(NMSImpl.java:800)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.util.NMS.registerEntityClass(NMS.java:222)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.npc.AbstractEntityController.<init>(AbstractEntityController.java:16)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.MobEntityController.<init>(MobEntityController.java:21)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.nms.v1_13_R2.entity.WolfController.<init>(WolfController.java:29)
03.12 18:46:09 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
03.12 18:46:09 [Server] WARN at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
03.12 18:46:09 [Server] WARN at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
03.12 18:46:09 [Server] WARN at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
03.12 18:46:09 [Server] WARN at java.lang.Class.newInstance(Class.java:442)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.npc.EntityControllers.createForType(EntityControllers.java:20)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:103)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:50)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.Citizens.reload(Citizens.java:362)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.commands.AdminCommands.reload(AdminCommands.java:44)
03.12 18:46:09 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
03.12 18:46:09 [Server] WARN at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
03.12 18:46:09 [Server] WARN at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
03.12 18:46:09 [Server] WARN at java.lang.reflect.Method.invoke(Method.java:498)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:155)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:87)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:183)
03.12 18:46:09 [Server] WARN at net.citizensnpcs.Citizens.onCommand(Citizens.java:238)
03.12 18:46:09 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
03.12 18:46:09 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:139)
03.12 18:46:09 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:699)
03.12 18:46:09 [Server] WARN at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1648)
03.12 18:46:11 [Multicraft] Skipped 44 lines due to rate limit (30/s)

**Comment by Florenthz** [comment]
@axemwa Yeah...  I have enabled lookclose and path but when I create a new npc, only move the head the first second, and when I asign a path, npc only walks every that I change him a new skin... Do i have to go to discord group?

**Comment by mcmonkey4eva** [comment]
@Florenthz post a new issue, don't post on this one (your issue has no relation to this issue thread)

**Comment by Florenthz** [comment]
Ok sorry... Im new in Github

**Comment by Florenthz** [comment]
Its ready:
https://github.com/CitizensDev/Citizens2/issues/1626

**Comment by axemwa** [comment]
@mcmonkey4eva Do you know whether or not citizens are supposed to shoot tipped arrows? I noticed this when my NPC's were attacking mobs with arrows, it seems like the arrows have effects on them. Was wondering if this was a citizens issue or not and whether if it's worth making and issue about it if it is? 

![image](https://user-images.githubusercontent.com/37608633/49695181-ea7e5d80-fbe6-11e8-87ec-eea2d2ba6269.png)

**Comment by mcmonkey4eva** [comment]
@axemwa that'd be a Sentinel issue if they're being fired by Sentinel, and that generally happens if you gave the NPC tipped arrows to shoot.

**Comment by axemwa** [comment]
Hmm the NPC's don't currently have any tipped arrows, just normal ones. I gave some to them in the past but I've removed then since then, is it possible a mob such as a skeleton could have fired it, but even then they only shoot normal arrows don't they so maybe not?

**Comment by axemwa** [comment]
@mcmonkey4eva is there a command or option in config where you can set a cooldown between individual NPC chat/messages

**Comment by mcmonkey4eva** [comment]
@axemwa I have no idea what that question is asking in the context of this issue.
If that question has no relation to this issue, ask on Discord https://discord.gg/Q6pZGSR or a separate issue

**Comment by axemwa** [comment]
sorry it was in no relation to this issue I was asking off topic but u right I should use discord instead for off topic questions

**Comment by mcmonkey4eva** [comment]
I believe this issue has been resolved.
It it hasn't, please reply below.

**Comment by axemwa** [comment]
No it's still occurring.
This is how the issue occurs

When the NPC/sentinel finishes attacking a phantom or the phantom dies from daylight, the head on the NPC stays stuck facing the air until either they find another target or when a mob attacks them first, then the head will look at the new enemy. 

Make sure to have lookclose off when testing this so that they player head doesn't look toward you which could make it seem like the head resetting is working fine, but with lookclose off and seeing the aftermath of attacking/chasing a bunch of phantoms I can see that the issue is still occurring.

___________________________________________________________________________________________________________
OFF-TOPIC

Ps: Just off-topic one time the npc got lost and couldnt get back to its set path because it went thru a gate that had a pressure plate in front of it but didnt have one on the other side to get back in, is there a way to make the NPC's open gates/doors that are obstructing it's path?

**Comment by mcmonkey4eva** [comment]
@axemwa what version of Citizens are you confirming this bug to still be on?
(Post output of `/version citizens` and `/version`)

`Ps: Just off-topic one time ` No. Post on Discord or a separate issue, don't spam issues with unrelated posts.

**Comment by axemwa** [comment]
wow....

**Comment by fullwall** [comment]
Fixed
