### ISSUE TITLE
Pushing NPCs through nether portal

### ISSUE THREAD

**Issue by orange451** [CitizensDev/Citizens2#1684]
I spawned a human type NPC in java, via:
`npcs.createNPC(EntityType.PLAYER, "Test")`

I then pushed him through a nether portal. He teleported after a few seconds, however when I teleported after him, he was not there. I then printed out his location in a repeating bukkit scheduled task, and saw that he was in fact in the nether. He still exists, and is pushable, but I cannot see him. Disconnecting and reconnecting does not fix the issue.

I'm using the current build of Citizens2. If you need any more information, let me know.

**Comment by mcmonkey4eva** [comment]
Can you replicate this without separate plugins, and only using in-game commands (like `/npc create Test`)

**Comment by orange451** [comment]
Using `/npc create test` creates an npc that is not pushable.

**Comment by mcmonkey4eva** [comment]
Possibly fixed in new builds by https://github.com/CitizensDev/Citizens2/commit/bbf3f281ebe9eaa0be76086ef566349f8246d57d

**Comment by BrodyBeckwith** [comment]
Can confirm that this still appears to be an issue on the latest version. However it seems under certain circumstances you can see the NPC while in other cases not. Additionally it seems under all cases the NPC is invulnerable to any damage despite setting protected false on world event and spawn event for the NPC.
