### ISSUE TITLE
Horse Riding + Speed

### ISSUE THREAD

**Issue by iCodeDreamsMC** [CitizensDev/Citizens2#2014]
Horse riding incorrectly.

https://one.denizenscript.com/haste/63541
https://www.youtube.com/watch?v=jmYupuTQvPM&feature=youtu.be
https://www.youtube.com/watch?v=W54bDLADZu8&feature=youtu.be

Horses move weirdly, they tp around sorta. They move incorrectly compared to other npcs. this was in testing environment with only citizens plugin. 

Speed Levels tend to do nothing https://youtu.be/aqDExw5t0h8
Slow speed: https://www.youtube.com/watch?v=W54bDLADZu8

2.0.26 (1804) VERSION

**Comment by mcmonkey4eva** [comment]
Actual versions since you broke the template:
`This server is running Paper version git-Paper-33 (MC: 1.15.1) (Implementing API version 1.15.1-R0.1-SNAPSHOT) ` + `Citizens v2.0.26-SNAPSHOT (build 1804) `

**Comment by raiderboy99** [comment]
I am having the same issue. Has anyone looked into this? I would like my rideable NPC's to go faster but they are stuck at one speed level and I checked horses and they are super glitchy.

**Comment by fullwall** [comment]
Try latest build

**Comment by lubcubsgaming** [comment]
This did fix the Horse Riding speed but did not fix the speed issue for any other NPC's...

**Comment by fullwall** [comment]
Can you try the latest build to see if there's any change to entity speed? I may change the approach here.

**Comment by lubcubsgaming** [comment]
I do not see any change to the NPC speed's.
I just recorded a clip using the latest build. The zombie speed's still seem to cap at level 5. And the horse speed's seem to work but when jumping with the horse they still increase their speed. I also showed in this video the horse getting stuck when trying to climb blocks, I was holding forward from 1:03 onward and I was getting stuck on the lower blocks.

https://youtu.be/3g5qqJOZKGA

**Comment by lubcubsgaming** [comment]
Just wanted to add onto this: Not sure if this is intended behavior or not. But setting any NPC speed to 0, just makes the controllable NPC  walk extremely slowly. I feel like it should stop the NPC from moving at all when a player is riding the NPC. Just my thoughts since you are looking into the speed values anyways.

**Comment by lubcubsgaming** [comment]
Just following up with this. Has there been any improvements to the system? Our server has gone live so we have been holding out on updating citizens until the issue has been fixed.

**Comment by fullwall** [comment]
Latest build should fix the issues.

**Comment by lubcubsgaming** [comment]
The horse issue does appear to be fixed but it has not fixed every other NPC. NPC's (other then horses) still can't be put past speed 5. And the horses speed 1 is about 5x the speed 1 of any other NPC.

**Comment by fullwall** [comment]
You can adjust the max speed in the config now. I can decrease the base horse speed.

**Comment by lubcubsgaming** [comment]
Thats perfect! Thanks!
