### ISSUE TITLE
Player Citizen skin resets to default on world change (e.g. to/from Nether) and on Bungee login

### ISSUE THREAD

**Issue by Vekseid** [CitizensDev/Citizens2#219]
The skin resetting issue appears to be a collection of issues, only one of which is present in Citizens out of the box.

To replicate:
- Default version of the latest Spigot 1.8 build, with default settings
- Latest dev build of Citizens
- Spawn a bunch of player NPCs with skins
- Build a nether portal right next to them.
- Step through, and back, skins have reset.
-- Edit: If you're having issues replicating, spawn npcs on both sides of the nether portal and bounce back and forth.

For Bungeecord:
- Latest build
- IP forwarding is on (and bungeecord=true in spigot.yml)
- As above, spawn a bunch of player npcs with skins, stand right next to them, and quit the default minecraft client completely.
- Start up the client again and sign into the bungeecord server. Skins will have reset. Sometimes a few may load.
- Logging out and back in, without quitting the client, will not cause skin resetting.

This isn't all of the skin resetting bugs. I've found that Bungeecord itself doesn't have any of the other reset bugs, so the others seem to be with my server's configuration somewhere.

Both of these are a bit different than the other reset bugs as they are usually all or nothing. They'll either reset completely or load perfectly.

----

As an aside, would it be possible to get a switch, when creating player npcs, to choose the default skin? This appears to be server controlled.

**Comment by mcmonkey4eva** [comment]
`/npc skin <whatever you like>`

**Comment by Vekseid** [comment]
?

The skins reset whether or not you've set another skin for them, that has nothing to do with the bug. Nor does it set the default if that's what you're referring to - it appears to be a property of the entity itself.

**Comment by jenks1999** [comment]
Seems like i get the same error even when i /npc skin <player name>

http://pastebin.com/rB8kZ9sc

this is a pastebin of it once. But i get it per npc.

**Comment by Vekseid** [comment]
Since installing the latest version of java on my client machine (not the server), this no longer occurs, even after removing it. So, that changed something, though I haven't been able to figure out what. Could hope it touched a file somewhere and this bug will eventually be moot.

There is still often a flash of the default skin when signing in, and in some other occasions, so being able to set the default would be nice to have. And for everyone who still has the bug on their client end.

**Comment by jenks1999** [comment]
updated java and still nothing. Using java version 7 update 76

**Comment by mcmonkey4eva** [comment]
@Vekseid the default skin (Steve/etc.) is loaded by Mojang code until the server loads and sends the new skin.

**Comment by mcmonkey4eva** [comment]
@jenks1999 That error is unrelated and caused by protocollib.

**Comment by Vekseid** [comment]
@mcmonkey4eva it's decided based on some property of entities by the server, though. It's consistent from viewer to viewer and I can get what I want by deleting and recreating them, it's just annoying.

I should not that since this fixed itself, they've all been showing up in my tab list. One for another, it seems.

**Comment by jenks1999** [comment]
mcmonkey4eva
huh? it was not my intention to hijack anything i thought this was the best place and tried to be as considerate as possible by looking around first and putting my info in the same are as a previously mentioned problem. I have updated protocollib and still the error spams like crazy, so i dont use npc's at the moment i assume?

**Comment by whoshenry** [comment]
This is still an issue when using the latest Citizens 2.0.15 and Spigot 1.8.3. When changing worlds, the npc skins revert back to Steve and Alex skins.

**Comment by adexgold** [comment]
I am also having trouble with the skins on the NPC, they loose their skins once a player dies and respawn, i have not tried switching worlds yet, i have all the latest builds i believe. I can cause the NPCs to reload the skins using the /npc skin command and also when i reload citizens in total. but this only fixes the NPCs that i am looking at, once i travel across town i can see a NPC that has lost the skin again. 

Also the problem is not persistent with multiple players, sometimes a player other than myself will see the skins when i dont and sometimes i see the skin and they dont.

**Comment by Vekseid** [comment]
This was fixed for a short period around January, but is now occurring again with the most recent Spigot/Bungeecord/Citizens builds.

It's not as bad as it was previously, at least.

**Comment by adexgold** [comment]
Yes it's nothing game breaking, just takes away a bit of the RPG feel in certain elements.

**Comment by Vekseid** [comment]
The latest build passes my stress test again. : )

**Comment by mcmonkey4eva** [comment]
Hooray, my patch worked :D

**Comment by tara81** [comment]
What patch fixes this issue ?

**Comment by mcmonkey4eva** [comment]
@tara81 https://github.com/CitizensDev/Citizens2/commits/master commits of April 6th

**Comment by tara81** [comment]
Dang I am still on 1.8.  Guess I have to upgrade soon
