### ISSUE TITLE
Citizens Skins resetting to default constantly.

### ISSUE THREAD

**Issue by Exoaria** [CitizensDev/Citizens2#359]
The /npc skin <name> is broken.

The skin is only in effect for clients that have had the NPC loaded in one of their visible chunks AT THE TIME of the name changing occuring.

This means if the skin is changed and someone joins the server, they see Steve. If the server /reload's, everyone sees Steve. If someone is away from the location the NPC was skinned at, when he is visible, they see Steve.

Skins are only visible to people who are in the direct vicinity of the NPC when the command is issued. The moment they leave and rejoin, they see Steve. Forever.

CraftBukkit 1.8.3
Citizens2 2.0.15

**Comment by mcmonkey4eva** [comment]
Update to latest dev build, this was fixed a while ago.

**Comment by Deathinflames** [comment]
I regret to inform that i to am still experiencing this issue.

This server is running CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
citizens-2.0.15-SNAPSHOT (build 1228)

**Comment by mcmonkey4eva** [comment]
@Deathinflames Are you in offline mode?

**Comment by Exoaria** [comment]
This is, indeed, a constant issue. It has improved, but 40% of the time when a chunk reloads or an NPC respawns, it will have the default skin.

**Comment by Deathinflames** [comment]
@mcmonkey4eva I am experiencing this issue with both online-mode=true and online-mode=false.

**Comment by ELJESTER** [comment]
I have the same problem as well! NPC skins constantly default until you either re log leave the area and come back or reload the plugin and even then it wont fix for a while! YES i am on the latest dev version of citizens, i check every day! and Latest spigot build, Skins used to be Perfect back in a really old build then when they were removed from the tab list they have become very unreliable!

**Comment by CKGAR** [comment]
I can confirm this. Also, when skins are present, the 3d sleeves and hat parts of the skin aren't shown. This is very disappointing. I've never ran a build of citizens where skins weren't an issue.

**Comment by mcmonkey4eva** [comment]
`the 3d sleeves and hat parts of the skin aren't shown. `
a previous bug report indicated this happens /in certain worlds but not all/

**Comment by mcmonkey4eva** [comment]
How are skins looking in 1.8.6, everyone?

**Comment by CKGAR** [comment]
I didn't hardcore testing, etc., but I did notice skins vanishing in the same manner they always have on the most recent build and Spigot 1.8.6. :/

**Comment by CKGAR** [comment]
*didn't do any

**Comment by seedie** [comment]
Happens very often in the latest dev build (1236), seems to be getting worse. It was fine for me on build 1217, however in that version the npcs names were cluttering up the tablist. If there is no fix i might need to downgrade to that version again. :8ball: Having steves everywhere greatly ruins the experience.

**Comment by CKGAR** [comment]
Ditto

**Comment by slingchilders** [comment]
Happens every couple of minutes on 1​23​9 and 1​23​8. Has any version been confirmed to not do this at all?

**Comment by mcmonkey4eva** [comment]
@slingchilders all the version prior to minecraft 1.7.6 were fine >.>

**Comment by Larycheese** [comment]
Hello, I am having the same issue as the above posters. I am using Spigot 1.8 and citizens-2.0.15-SNAPSHOT (build 1228). 

Is there anything you can do/ are working on to fix it? 

Really need this for my server- it's the best plugin out there except for this. 

So here's the gist of it. I'm using Spigot 1.8, Citizens 2 - (citizens-2.0.15-SNAPSHOT.jar and Hypermerchant/Hypereconomy.

I changed my NPC skins to actual real life player names- and it worked great! ... until about 30 minutes after I set their skin, they revert back to Steve (or Alex) in some cases.I could not find a rhyme or reason why this would happen. It appears to happen at random, and certain NPCs revert more frequently than others.

I have researched online but couldn't find any information on this issue until now. So glad I found this thread!

I am hosted online via Bisecthosting.com

Maybe it is a conflicting plugin?
Here is a list of what I am using in case that helps. If not, sorry for TMI :
AntiFire
Bettershops (still installed but not using it)
BuyRegion
ChatManager
Citizens2
CoreProtect
EssentialsGroupManager
FirstJoinPlus
HyperConomy
Hypermerchant
iConomy (my preferred economy plugin)
Jail
JustWarp
LWC
MaintenanceMode
McJobs
MultiHome
Protocollib
SilkSpawner
SilkSpawnerEco
Simple Prefix
SimpleMobCatcher
SimpleTicketManager
SketchMap
TeleportSuite
TreeAssist
Vault
WorldEdit
WorldGuard

Thank you so much for your time. I apologize for inconveniencing you.

**Comment by Larycheese** [comment]
Hey Guys, sorry for the double post; but I adjusted my settings and found something may help. It's not groundbreaking by any means, and it's not perfect- they still despawn- but changing this configurations has made it happen a lot less frequently, and they fix themselves faster when it does. 
1. Change 'check game version' to false
2. Change 'Chunks: always-keep-loaded' to true
3. Change 'retry delay' to 0! 

They still revert to steve, but when you enter the chunk they usually fix themselves before you see them, which is nice. Still hoping for a permanent fix though :) Hope this helps someone.

**Comment by seedie** [comment]
Thanks for your reply, these changes did improve the situation but as you said i would prefer a permanent fix. I dont think any of your plugins are the issue as we only have four in common:

**Comment by mcmonkey4eva** [comment]
How's this looking on latest dev builds?

**Comment by CKGAR** [comment]
Good. The most recent dev builds (when I was using them, I've been having to use #1257 because of a compatibility issue with the plugin I use called BetterShops, the dev is inactive and the Citizens hook is broken on the very most recent builds) seem to have no issues with skins. The build I'm using is still pretty good, I've only seen NPCs lose their skins like once or twice on #1257.

**Comment by JohOply** [comment]
Hi guys !

I already have the bug, even if I use /npc skin playername -p ^^
After some time (10 days~?), if "playername" changed his skin, NPC take the new skin.

**Comment by mcmonkey4eva** [comment]
@JohOply try the latest Citizens dev builds at http://ci.citizensnpcs.co/job/Citizens2/

ATM the site appears to be not responding, but it should be back up soon.

Worst case scenario if it's not up in a few days, send a message here and I'll dropbox a copy for ya.

**Comment by JohOply** [comment]
Hi,

In latest (b1272), server crash when i use /npc create
http://pastebin.com/S7Dq6VJ1

**Comment by JohOply** [comment]
In my server, i use b1267 (beta 1), and sometimes i have error, like it (i don't know why it happens): 

[16:31:49 ERROR]: Could not pass event NPCSpawnEvent to Citizens v2.0.16-SNAPSHOT (build 1267)
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:213) [Citizens-2.0.16-b1.jar:?]
at net.citizensnpcs.EventListen.spawn(EventListen.java:497) [Citizens-2.0.16-b1.jar:?]
at net.citizensnpcs.EventListen.respawnAllFromCoord(EventListen.java:474) [Citizens-2.0.16-b1.jar:?]
at net.citizensnpcs.EventListen.onChunkLoad(EventListen.java:129) [Citizens-2.0.16-b1.jar:?]
at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor$Task.finish(AsynchronousExecutor.java:188) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.finishActive(AsynchronousExecutor.java:347) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:34) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:734) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.IllegalArgumentException: Cannot measure distance between BuildBattle and Eldorado
at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.citizensnpcs.npc.skin.SkinUpdateTracker.resetNearbyPlayers(SkinUpdateTracker.java:223) ~[?:?]
at net.citizensnpcs.npc.skin.SkinUpdateTracker.onNPCSpawn(SkinUpdateTracker.java:139) ~[?:?]
at net.citizensnpcs.EventListen.onNPCSpawn(EventListen.java:354) ~[?:?]
at sun.reflect.GeneratedMethodAccessor70.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_45-internal]
at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_45-internal]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
... 24 more
[16:31:50 WARN]: [Citizens] Task #60477 for Citizens v2.0.16-SNAPSHOT (build 1267) generated an exception
java.lang.IllegalArgumentException: Cannot measure distance between Eldorado and BuildBattle
at org.bukkit.Location.distanceSquared(Location.java:456) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.citizensnpcs.npc.skin.SkinPacketTracker.updateNearbyViewers(SkinPacketTracker.java:189) ~[?:?]
at net.citizensnpcs.npc.skin.SkinPacketTracker$1.run(SkinPacketTracker.java:114) ~[?:?]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8-b565.jar:git-Spigot-5f38d38-18fbb24]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]

**Comment by mcmonkey4eva** [comment]
iConomy's fault there, it got stuck trying to connect to your SQL database.

**Comment by JohOply** [comment]
Rahh! I use iconomy only on my test server, i will try again ^^

**Comment by JohOply** [comment]
I didn't see this problem anymore, so i think it is fixed :) If i see it again, i will open a new ticket :)

**Comment by JohOply** [comment]
Hi,

Finally, there is a problem, but less important that the first. Sometimes, skin doesn't load correctly. Example : 

My NPC : http://i.imgur.com/QpCa1pY.png
Sometimes, the bug : http://i.imgur.com/Ba1dUlw.png

If i leave then i comeback, the skin reappear. I use b1272 and i set the skin with " -p "

**Comment by leasoncre** [comment]
i have the same problem. (-p doesn't work)

git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT), Citizens version 2.0.16-SNAPSHOT (build 1274)

i think it's related to the '-p' thing. my thought process is that the -p is supposed to save the skin serverside and load the skin to the npc whenever it's loaded/called/etc.. i'm not sure if they fixed this yet. but i think it's a known problem. please fix. hard to make good npcs when they keep changeing skins. (or steve skin is stuck on 'em too for no reason...)

**Comment by fullwall** [comment]
The -p flag saves the skin snapshot yes. I will look into it.

**Comment by fullwall** [comment]
Just tried and it worked for me. The signature may be expiring - does the problem only occur after some time?

**Comment by leasoncre** [comment]
hymm.. i think this was fixed in one of the latest dev builds. latest release may still have this bug though.

**Comment by CKGAR** [comment]
I can confirm it is happening again in the same manner it was before. It doesn't happen after a certain time. All you have to do is look away from the NPC and look back and the skin is gone. I don't even think you have to leave the area for it to happen. I'm running the latest dev build and the latest Spigot version.

**Comment by fullwall** [comment]
@CKGAR unfortunately I still can't seem to reproduce... could you please post a list of plugins and your server config?

**Comment by fullwall** [comment]
@JCThePants after looking into the code I noticed some comparisons with unnormalised yaw (lower bound and upper bounds are never normalised using clampYaw but doing a straight clampYaw would break the current logic). Isn't this a problem?

**Comment by JCThePants** [comment]
@fullwall After reviewing it I agree it's a problem, although minor.

It works on the assumption that if the lower bound is less than -180, the upper bound check will catch the players clamped yaw and if the upper bound is greater than 180, the lower bound will catch.
I think under some circumstances, there will be a range at the opposite end where the skin will update sooner than expected.

I won't be able to contribute anytime soon, I've been very busy.

**Comment by JCThePants** [comment]
@fullwall I've created a node.js script to demonstrate and test a working version of the algorithm. I apologize I can't push directly.

https://gist.github.com/JCThePants/cd3430d105ca67959b5c

**Comment by fullwall** [comment]
@JCThePants no worries, just trying to reproduce / debug this issue. Thanks for the gist, I appreciate it.

**Comment by Devotedworker** [comment]
Have yet to see the bug re-appear in Latest Version. Solved?

**Comment by fullwall** [comment]
@Devotedworker keep getting the odd report though...

**Comment by CKGAR** [comment]
Whatever y'all did on the latest dev build, it's working. I have yet to see skins disappear, and even many plugins that had a broken or faulty hook into Citizens now magically work again. I hate to speak too soon, but bravo!

**Comment by maxlehot1234** [comment]
Any way to make player skin work with a png ? Like imgur, dropbox directlink?
It can be very useful to create my own skin and pu them on dropbox and use them on the server... 

The first time, citizens go ge it on the itnernet,next time, it was save on the server...

Thanks

**Comment by mcmonkey4eva** [comment]
Nope. Mojang does not allow that.

**Comment by CKGAR** [comment]
This issue with the same symptoms is happening again on the latest dev build of Citizens and latest Spigot version.

**Comment by CKGAR** [comment]
This issue with the same symptoms is happening again on the latest dev build of Citizens and latest Spigot version.

**Comment by CKGAR** [comment]
Yo, you seemed to have missed this^ Don't know the reason to be hella snobby about it was, but ok. Sorry if I seem angered, this literally has been an issue on all of but a few builds of Citizens for me*

*and no, I'm not new to Citizens.

**Comment by doitliketyler** [comment]
This is still happening with the latest build.

**Comment by fullwall** [comment]
@doitliketyler plugin list?

**Comment by CKGAR** [comment]
This is still a problem on the most recent builds. Plugin conflicts aren't the issue. It occurs even when on a test server with no other plugins. Still, I use it on 3 different servers all with different plugins, yet the problem persists.

**Comment by fullwall** [comment]
@CKGAR - can you turn on debugging and pastie the log file?

**Comment by CKGAR** [comment]
@fullwall http://pastebin.com/TJ3x5SUX

**Comment by mcmonkey4eva** [comment]
@CKGAR I think he wants a debug log that includes the problem occurring...

**Comment by CKGAR** [comment]
@mcmonkey4eva how do I obtain that

**Comment by mcmonkey4eva** [comment]
@CKGAR run your server and either trigger the problem or wait for it to happen, then pastebin the full logs. Probably not using a live public instance of your server for that.

**Comment by CKGAR** [comment]
@mcmonkey4eva The problem happened and nothing showed up, just "Fetched due players..." etc. http://pastebin.com/TeyNammY

**Comment by mcmonkey4eva** [comment]
Skins are funky in general.
Reference this for information on skin handling: https://wiki.citizensnpcs.co/Skins
if issues outside of the inevitable happen, please open a new issue
