### ISSUE TITLE
Skins bugged with build #1213

### ISSUE THREAD

**Issue by rewtie** [CitizensDev/Citizens2#439]
Over half of the time skins aren't showing up on the NPC's. There are three different way's they will show up.. Either it will work fine, it will be the new Alex skin for 1.8, or it will give you some deformed version of the steve skin. 

Here's a picture of an example of the skins not showing up: http://i.imgur.com/zwQs63C.png

Here's a close up picture of the steve skin (the face is half invisible): http://i.imgur.com/CCtiFCn.png

I'm running 1.8 spigot with citizens build #1213.

**Comment by Talamar1** [comment]
There were a lot of skin issues in 1.8, some caused by Mojang.  Almost all of these are fixed if you upgrade your server to the latest version of Spigot and the latest version of Citizens (1247).

**Comment by logicalPolaris** [comment]
I'm on latest spigot and citizens, and even though it seems that it's better skin-wise, there are still times where the NPC skin won't load for people.

**Comment by logicalPolaris** [comment]
This bug is still occuring on 1.8.7 Spigot and Citizens build #1251

**Comment by mcmonkey4eva** [comment]
How about latest dev builds?

**Comment by mcmonkey4eva** [comment]
Post below if this issue needs to be reopened.
