### ISSUE TITLE
reload command doesn't reload npcs in unloaded areas

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#660]
citizens build 1308, git-Spigot-e4d4710-e1ebe52 1.8.8

when i run the /citizens reload command npc's not near a logged-in player do not reload. (they don't re-spawn-in)

Example, not exact: i'm in adventure world (-1000x63x-1000) run the command from there, only npcs in chunks loaded by me re-spawn. npc's @ Adventure world 1000x63x1000 /and/ world world 0x63x0 don't/haven't reload if i teleport/warp/home to the area they are in.

only way to get ALL the npc's to load up is with a server restart/reload

**Comment by mcmonkey4eva** [comment]
... what do you mean? If they're not spawned, the reload command isn't going to spawn them...

**Comment by leasoncre** [comment]
they are spawned. but when i do citizens reload and no-ones around the spawned npc's they don't spawn

**Comment by fullwall** [comment]
Can you give a plugin list? Can't reproduce this....

**Comment by leasoncre** [comment]
Plugins (53): QfCore, JoeIPTracker, ClearChat, GroupManager, MobEggSpawnerBlocker, ScheduledAnnouncer2, AntiWorldFly, SimpleTicketManager, VoxelSniper, ChestRegen, Ping, Titlebar, AsyncWorldEditInjector, CoreProtect, PlayerHeads, dynmap, WorldEdit, VoteRoulette, OpenInv, Chairs, Votifier, ActionBarAPI, Multiverse-Core, ProtocolLib, LibsDisguises, BlocksHub, mcMMO, Vault, BlocksHub-CoreProtect, HolographicDisplays, LWC, WorldGuard, MythicMobs, BlocksHub-WorldGuard, Multiverse-NetherPortals, Commandspy, CustomEnchantments, Essentials, Dynmap-WorldGuard, Citizens, AsyncWorldEdit, AsyncWorldEdit-ActionBarAPI, EssentialsChat, Signs, ColoredTablist, SuperVanish, EnjinMinecraftPlugin, Dynmap-Essentials, Sentry, BetonQuest, EssentialsProtect, ServerSigns, EssentialsSpawn

(EssentialsX; qfcore is private plugin, does nothing with npcs)

**Comment by fullwall** [comment]
Can you try disabling Multiverse, CoreProtect, MythicMobs and seeing if the problem persists?

**Comment by leasoncre** [comment]
problem exists in 1.9 as well.
-git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
-Citizens version 2.0.17-SNAPSHOT (build 1326)
disabled multiverse, (coreprotect removed), and mythic mobs, problem persists

1, create npcs nearby
2. fly off ~1000 blocks or guessing 50chunks
3. make more npc's
4. /citizens save
5. /back to first spot
6. /citizens reload  (nearby npcs reload)
7. /back to 2nd set of npcs (npc's not loaded)
8. /citizens reload (nearby npc's load)
9. /back to 1st set of npcs (npc's not loaded)

**Comment by fullwall** [comment]
Should be fixed.

**Comment by leasoncre** [comment]
it's not fixed

**Comment by mcmonkey4eva** [comment]
This is most likely not still an issue (and either way the reload command shouldn't be used unless you particularly need it for something)
