### ISSUE TITLE
ghost npcs

### ISSUE THREAD

**Issue by leasoncre** [CitizensDev/Citizens2#677]
git-Spigot-b1c1b55-7d330bc (MC: 1.9) (Implementing API version 1.9-R0.1-SNAPSHOT)
Citizens version 2.0.17-SNAPSHOT (build 1326)
Sentry version 1.9.0
Plugins (43): AsyncWorldEditInjector, VoteRoulette, JoeIPTracker, OpenInv, GroupManager, MobEggSpawnerBlocker, Chairs, Votifier, ActionBarAPI, SimpleTicketManager, ProtocolLib, LibsDisguises, HeadMap, VoxelSniper, BlocksHub, TrophyHeads, mcMMO, Vault, Commandspy, Titlebar, dynmap, Essentials, HolographicDisplays, LWC, Citizens, AsyncWorldEdit, EssentialsProtect, EssentialsChat, ServerSigns, ColoredTablist, EssentialsSpawn, EnjinMinecraftPlugin, WorldEdit, Denizen, Dynmap-Essentials, Sentry, WorldGuard, mcMMO-WorldGuard, BlocksHub-WorldGuard, Signs, Builder, Dynmap-WorldGuard, BetonQuest

---

doing some testing and added sentry to one of my npcs and this happened: (ghost/duplicated npcs on plugin reload)
https://gyazo.com/d4e0f9f5f0dbc1c37b58c39049a14e94 (you can barely see that there is 2 ghost npcs by looking at thier shoulders)

```
/npc create test
[[Stop server, start server]]<<--important, not replicable without doing this
/npc sel
'selected test'
/trait sentry
/npc path
(click 4 points)
(noticed this time he isn't skipping through the world like i reported in #633 , stared in awe for a moment)
/citizens save
/citizens reload
(confusion at there being an npc standing still where i first spawned him in, AND the same one runs around the waypoints)
/citizens reload
(notice another ghost npc appears)
/npc sel (aiming at static npc)
'you selected test'
/npc remove
(walking npc dissapears)
/npc sel
'you selected test'
/npc remove
'you must have an npc selected to do that!'
(even more confusion...)

('ghost' npcs are not re-spawned on server restart, temporary)

```

NOTE: may be related to #660

**Comment by leasoncre** [comment]
this appears to be a duplicate of #605

**Comment by fullwall** [comment]
Should be fixed with newest Sentry build, reopen if not.

**Comment by leasoncre** [comment]
[i don't have perms to re-open a closed ticket]

it's not quite fixed.... it's not instantly dup-ing the npcs now. it just takes a moment (about 3-5 seconds)
however, it seems to only be duping the npc's once, regardless of how many times /citizens reload is run

**Comment by leasoncre** [comment]
see also: [sometimes happens, sometimes doesn't]
on shutdown:

```
[05:36:19] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[05:36:19] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin Citizens v2.0.17-SNAPSHOT (build 1330) generated an exception while executing task 7665
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalStateException: no implementation set
	at net.citizensnpcs.api.CitizensAPI.getImplementation(CitizensAPI.java:65)
	at net.citizensnpcs.api.CitizensAPI.getPlugin(CitizensAPI.java:103)
	at net.citizensnpcs.npc.profile.ProfileRequest.setResult(ProfileRequest.java:108)
	at net.citizensnpcs.npc.profile.ProfileFetcher$1.onProfileLookupFailed(ProfileFetcher.java:66)
	at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:77)
	at net.citizensnpcs.npc.profile.ProfileFetcher.fetchRequests(ProfileFetcher.java:47)
	at net.citizensnpcs.npc.profile.ProfileFetchThread.run(ProfileFetchThread.java:88)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
```

**Comment by mcmonkey4eva** [comment]
@leasoncre can you test this with Sentry disabled?

**Comment by leasoncre** [comment]
does not happen without sentry. (i actually see them despawn before they re-spawn)

**Comment by mcmonkey4eva** [comment]
Sentry doesn't exist anymore so... issue fixed!
