### ISSUE TITLE
NPC rotation issues

### ISSUE THREAD

**Issue by Brokkonaut** [CitizensDev/Citizens2#983]
In the latest version player npcs don't look at you if /npc lookclose is activated. They just look in the same direction all the time. Even with /npc tphere they don't change the direction they are looking at.

**Comment by drekryan** [comment]
As with every Citizens build something that was working fine has to be broken. I dont think the people actually submitting the code are actually testing it so here you go I will help. Here are two instances of how broken lookclose is now.

First:
https://gyazo.com/a80af88a1b3fff5318c8ef4717f4d113

Look Close works best when they actually look at you. Which every npc no longer does.

Second:
https://gyazo.com/738f95bc71275be3295de355007340ce

You gave a few too many drinks to my perfectly fine snowman. What is wrong with him?

**Comment by mcmonkey4eva** [comment]
Sorry @drekryan our lead developer is rather busy and doesn't always have time to test as thoroughly as possible. Thankfully, users like you two are here to point out what was missed and help us get it fixed :)

**Comment by fullwall** [comment]
Try latest build?

**Comment by drekryan** [comment]
@fullwall @mcmonkey4eva Please reopen this. I am still having both issues mentioned in my comment on this issue. There is literally no change between the previous build and the latest.

**Comment by Brokkonaut** [comment]
Now it is more bugged than before.. they just circle the head around (but don't look at the player) and the body does not rotate at all

**Comment by fullwall** [comment]
Try latest build @Brokkonaut.

@drekryan sorry, got thrown off by the issue title.

**Comment by Brokkonaut** [comment]
Still not working for all NPCs. Some NPCs with lookclose just rotate around very fast - But now also the body rotates.. I think it depends on the direction you approach them, if they will rotate or look at you.

**Comment by tincxd** [comment]
I have the sam problem with lookclose command ... they just go crazy and dont look at you at all ... pls fix asap :)

**Comment by mcmonkey4eva** [comment]
Seems to affect 1.10 as well!

**Comment by Sikatsu** [comment]
#977 

Exactly my issue too.

**Comment by MusicScore** [comment]
Same issue, Player NPCs do not rotate properly. Mob-type NPCs do rotate correctly in respect to the yaw, but their pitch is broken. If I stand one block above it, it will look one block below me.

**Comment by fullwall** [comment]
The pitch bug should be fixed in build 1439. I can't reproduce the spinning thing - any tips? (entity type/player position etc)

**Comment by fullwall** [comment]
Try build 1440 for a possible spinning fix.

**Comment by MusicScore** [comment]
Tested with a Villager NPC with latest build. It doesn't look at the player properly half the time, and its head movement in respect to the yaw is not fluid. Its head rotation in respect to the pitch is working fine, though.

**Comment by fullwall** [comment]
@MusicScore build 1441? works for me.

**Comment by MusicScore** [comment]
Villager NPCs still do not rotate properly. Rigorous testing on a Skeleton/Zombie NPC makes its head violently snap at random angles. Player NPCs apparently do not rotate their heads at all. Player NPC bodies rotate at a constant rate, and do not correlate to the position of the actual player.

**Comment by fullwall** [comment]
Try 1442 for the villager bug, I am aware that player NPC bodies aren't ending up square to their target, just need to figure out where in the code that is.

**Comment by MusicScore** [comment]
Villager rotation is okay. It's still jumpy/nonfluid in respect to the yaw, but its rotation is accurate.

**Comment by drekryan** [comment]
Agreed that the title of this issue doesn't really fit what the issue has turned into. It doesn't just happen to player NPCs as the title states. It's a much bigger issue than just that. However I felt it was best to tack my findings under it instead of opening a new issue. The wording of the title couldn't hurt from being updated however

**Comment by drekryan** [comment]
What's the status on this issue?

**Comment by fullwall** [comment]
I have fixed some of your issues @MusicScore. Players are working for me currently so not sure on that one.

**Comment by Brokkonaut** [comment]
At least one bug still exists: If no player is close to citizen with "lookclose", the citizen is always looking in south direction. in previous versions he stayed looking in the direction the player was before.

**Comment by MusicScore** [comment]
On Spigot 1.10, the problems appear to still persist.

On Spigot 1.11, Player NPCs work. The rotation delay with Horses, Magma Cubes, Slimes, and Ghasts persists, but I'm not too bothered by it.  Polar Bears now have the same rotational delay as the above four mentioned mobs (meaning they don't take ten years to rotate). Ender Dragons, Guardians, Silverfishes, Endermites, and Bats appear to be fixed.

On both versions, the rotation can be a bit sticky with respect to the yaw (it jitters sometimes), but I'm not so concerned with that.

**Comment by fullwall** [comment]
Thanks, I will look into these issues tonight. It seems that Minecraft has added some local render yaw delay which may explain these rotation delay issues.

**Comment by MusicScore** [comment]
Can confirm that Player NPCs work on 1.11. All rotation issues on 1.10 still exist.

**Comment by NASH0XX** [comment]
Having this same issue in 1.10.2 spigot with latest build.



Please fix it, thx.

**Comment by fullwall** [comment]
@NASH0XX which build is that?

**Comment by Nutty101** [comment]
using net.citizensnpcs.util.Util.faceLocation(npc.getEntity(), {location}) does not seem to change their direction at all anymore. 1.10 / 1.11 on build 1456. 1420 they work in 1.10.

**Comment by fullwall** [comment]
@Nutty101 check latest build.

**Comment by Nutty101** [comment]
That fixed it! Close this one out :)
