### ISSUE TITLE
CitizensAPI setTarget only follows the X and Z direction

### ISSUE THREAD

**Issue by kinukin** [CitizensDev/Citizens2#989]
Bug

Location loc = spawnLocation.get(e.getNPC().getName());
e.getNPC().getNavigator().setTarget(loc);

In the Citizens API, the npc does not follow the location coordinates accordingly and only goes to the X and Z coordinates, ignoring the Y coordinate. 

For example, if a building was a 2 story house and the npc was spawned on the first level. And the npc moved to the second level and if the location is set back to its original coordinates it would go to the designated coordinates of the original coordinates except it won't go back to the first level. It would be on the second level but in the same position as the first level.

Minecraft Version 1.11, Citizens Version  2.0.21-SNAPSHOT <build 1426>

**Comment by fullwall** [comment]
Can you screenshot your path?

**Comment by kinukin** [comment]
This is how I'm setting the target

Set location to these coordinates and spawn on these coordinates
<a href='https://postimg.org/image/5xna2eup9/' target='_blank'><img src='https://s14.postimg.org/fuyavh2b5/spawnlocation.jpg' border='0' alt='spawnlocation'/><br /><a target='_blank' href='https://postimage.org/'></a><br /><br />

then If a player attacks the NPC, follow the player and attack the player until health is below 15

e.getNPC().getNavigator().setTarget(p, true); // aggressively attack to player

then set location back to original spawn position after attacking player
public static Map<String, Location> spawnLocation = new HashMap<String,Location>(); 
spawnLocation.put(npc.getName(), npc.getEntity().getLocation()); //put original location into hashmap

//load location from hashmap and set target to original location
Location loc = spawnLocation.get(e.getNPC().getName());
e.getNPC().getNavigator().setTarget(loc);

Location set back to original position (spawnLocation) -

<a href='https://postimg.org/image/xxicmy3ul/' target='_blank'><img src='https://s22.postimg.org/cb3c5x5a9/spawn_Location2.jpg' border='0' alt='spawnLocation2'/><br /><a target='_blank' href='https://postimage.org/'></a><br /><br />

The npc is just directly below the original coordinates, when the npc should be on the original coordinates.

pink wool = the original spawn location of the npc. 
below = wrong position
<a href='https://postimg.org/image/v9ybhrgq5/' target='_blank'><img src='https://s22.postimg.org/5r5z4qx69/2016_11_28_00_32_35.png' border='0' alt='2016-11-28_00.32.35'/><br /><a target='_blank' href='https://postimage.org/app.php'></a><br /><br />

**Comment by kinukin** [comment]
So basically it when you try to set the location to getStoredLocation(); it breaks

**Comment by kinukin** [comment]
Is there an issue within the npc.getNavigator().setTarget(npc.getStoredLocation());  code?

**Comment by fullwall** [comment]
@kinukin getStoredLocation() is always updated to the NPC's current location - it's for when the NPC is despawned and you want to know its last known location. The code you gave doesn't mention getStoredLocation(), but it's not the location you spawn the NPC at so you shouldn't use it like that.

**Comment by kinukin** [comment]
Okay, I'll just stick with saving the original position in a hashmap when the npc is spawned. By the way, is there a problem if setTarget(location)? The npc doesn't seem to head properly to the set location.

**Comment by fullwall** [comment]
Have you been using the new pathfinder? If so I just pushed a fix for it.

**Comment by kinukin** [comment]
Ah, yes I'm using the latest build of Citizens. The same problem still occurs.
Citizens-2.0.21-SNAPSHOT.jar

**Comment by kinukin** [comment]
after checking if the npc was not in the original location after setting its target to the original location, it appears the npc is having a hard time distinguishing the x,y and z coordinates.

The npc knows that it's in the wrong location but it doesn't know how to get there.

**Comment by Nutty101** [comment]
After looking into issues on a couple servers, we are finding that the Y axis isn't respected. So you can set targets and it will say its there, but it will stay on the current level and act like it reached that location when it's in fact still +5 on the y axis. Causing issues with getting NPC's to go where they should go. 

Video of the issue:
https://youtu.be/4A6lRbdAnjY

**Comment by fullwall** [comment]
@Nutty101 it seems to be a problem with the Minecraft pathfinder, have been looking through its code today but haven't tracked down the issue yet. It is getting the right destination and everything it just seems to not look for blocks in all directions very well.

**Comment by fullwall** [comment]
@Nutty101 it may be to do with the stairs.

**Comment by Nutty101** [comment]
Ahh, that might make sense. I will setup a non stair version tomorrow. Crashing out for tonight :)  Thanks for looking at it.

**Comment by File14** [comment]
I think I have the same issuse: https://github.com/CitizensDev/Citizens2/issues/1038
